[tools]
python = "3.14"
uv = "0.9"

[settings]
python.uv_venv_auto = true

[env]
_.python.venv = { path = ".venv", create = true }
ANSIBLE_COLLECTIONS_PATH = "{{ config_root }}/.ansible"

[tasks.install]
description = "install prerequisites"
alias = "i"
run = """
uv pip install -r requirements.txt
"""
